//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 10:26:03 AM IST 
//


package com.Thd.Request.JavaBeans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An BOPIS_Create_Order_Object_Factory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class BOPIS_Create_Order_Object_Factory {


    /**
     * Create a new BOPIS_Create_Order_Object_Factory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public BOPIS_Create_Order_Object_Factory() {
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Extn.HDStorePaymentInfoList.HDStorePaymentInfo }
     * 
     */
    public BOPIS_Create_Order.Extn.HDStorePaymentInfoList.HDStorePaymentInfo createOrderExtnHDStorePaymentInfoListHDStorePaymentInfo() {
        return new BOPIS_Create_Order.Extn.HDStorePaymentInfoList.HDStorePaymentInfo();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines }
     * 
     */
    public BOPIS_Create_Order.OrderLines createOrderOrderLines() {
        return new BOPIS_Create_Order.OrderLines();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.OrderDates }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.OrderDates createOrderOrderLinesOrderLineOrderDates() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.OrderDates();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order }
     * 
     */
    public BOPIS_Create_Order createOrder() {
        return new BOPIS_Create_Order();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Extn.HDWillCallList }
     * 
     */
    public BOPIS_Create_Order.Extn.HDWillCallList createOrderExtnHDWillCallList() {
        return new BOPIS_Create_Order.Extn.HDWillCallList();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Instructions }
     * 
     */
    public BOPIS_Create_Order.Instructions createOrderInstructions() {
        return new BOPIS_Create_Order.Instructions();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.PersonInfoBillTo }
     * 
     */
    public BOPIS_Create_Order.PersonInfoBillTo createOrderPersonInfoBillTo() {
        return new BOPIS_Create_Order.PersonInfoBillTo();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall.HDWCLineStatusList.HDWCLineStatus }
     * 
     */
    public BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall.HDWCLineStatusList.HDWCLineStatus createOrderExtnHDWillCallListHDWillCallHDWCLineStatusListHDWCLineStatus() {
        return new BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall.HDWCLineStatusList.HDWCLineStatus();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.PaymentMethods }
     * 
     */
    public BOPIS_Create_Order.PaymentMethods createOrderPaymentMethods() {
        return new BOPIS_Create_Order.PaymentMethods();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.LinePriceInfo }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.LinePriceInfo createOrderOrderLinesOrderLineLinePriceInfo() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.LinePriceInfo();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall }
     * 
     */
    public BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall createOrderExtnHDWillCallListHDWillCall() {
        return new BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Extn.HDStorePaymentInfoList }
     * 
     */
    public BOPIS_Create_Order.Extn.HDStorePaymentInfoList createOrderExtnHDStorePaymentInfoList() {
        return new BOPIS_Create_Order.Extn.HDStorePaymentInfoList();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.PersonInfoShipTo }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.PersonInfoShipTo createOrderOrderLinesOrderLinePersonInfoShipTo() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.PersonInfoShipTo();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.Item }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.Item createOrderOrderLinesOrderLineItem() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.Item();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Instructions.Instruction }
     * 
     */
    public BOPIS_Create_Order.Instructions.Instruction createOrderInstructionsInstruction() {
        return new BOPIS_Create_Order.Instructions.Instruction();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.Extn.HDEventList.HDEvent }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.Extn.HDEventList.HDEvent createOrderOrderLinesOrderLineExtnHDEventListHDEvent() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.Extn.HDEventList.HDEvent();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.LineTaxes }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.LineTaxes createOrderOrderLinesOrderLineLineTaxes() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.LineTaxes();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.OrderDates.OrderDate }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.OrderDates.OrderDate createOrderOrderLinesOrderLineOrderDatesOrderDate() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.OrderDates.OrderDate();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Extn }
     * 
     */
    public BOPIS_Create_Order.Extn createOrderExtn() {
        return new BOPIS_Create_Order.Extn();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.Extn.HDEventList }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.Extn.HDEventList createOrderOrderLinesOrderLineExtnHDEventList() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.Extn.HDEventList();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.LineTaxes.LineTax }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.LineTaxes.LineTax createOrderOrderLinesOrderLineLineTaxesLineTax() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.LineTaxes.LineTax();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine createOrderOrderLinesOrderLine() {
        return new BOPIS_Create_Order.OrderLines.OrderLine();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.OrderLines.OrderLine.Extn }
     * 
     */
    public BOPIS_Create_Order.OrderLines.OrderLine.Extn createOrderOrderLinesOrderLineExtn() {
        return new BOPIS_Create_Order.OrderLines.OrderLine.Extn();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall.HDWCLineStatusList }
     * 
     */
    public BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall.HDWCLineStatusList createOrderExtnHDWillCallListHDWillCallHDWCLineStatusList() {
        return new BOPIS_Create_Order.Extn.HDWillCallList.HDWillCall.HDWCLineStatusList();
    }

    /**
     * Create an instance of {@link BOPIS_Create_Order.PaymentMethods.PaymentMethod }
     * 
     */
    public BOPIS_Create_Order.PaymentMethods.PaymentMethod createOrderPaymentMethodsPaymentMethod() {
        return new BOPIS_Create_Order.PaymentMethods.PaymentMethod();
    }

}
