//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 04:30:28 PM IST 
//


package com.Thd.Request.JavaBeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Extn">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnDerivedTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnHostOrderSystemIdentifier" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipmentLines">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ShipmentLine">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Extn">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="ExtnHostOrderLineReference" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                     &lt;attribute name="ExtnTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ExtnSKUCode" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="ExtnSVSRemEntriesReqd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="EnterpriseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SellerOrganizationCode" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="ShipNode" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extn",
    "shipmentLines"
})
@XmlRootElement(name = "Shipment")
public class Final_Release_Request {

    @XmlElement(name = "Extn", required = true)
    protected Final_Release_Request.Extn extn;
    @XmlElement(name = "ShipmentLines", required = true)
    protected Final_Release_Request.ShipmentLines shipmentLines;
    @XmlAttribute(name = "EnterpriseCode")
    protected String enterpriseCode;
    @XmlAttribute(name = "SellerOrganizationCode")
    protected Short sellerOrganizationCode;
    @XmlAttribute(name = "ShipNode")
    protected Short shipNode;

    /**
     * Gets the value of the extn property.
     * 
     * @return
     *     possible object is
     *     {@link Final_Release_Request.Extn }
     *     
     */
    public Final_Release_Request.Extn getExtn() {
        return extn;
    }

    /**
     * Sets the value of the extn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Final_Release_Request.Extn }
     *     
     */
    public void setExtn(Final_Release_Request.Extn value) {
        this.extn = value;
    }

    /**
     * Gets the value of the shipmentLines property.
     * 
     * @return
     *     possible object is
     *     {@link Final_Release_Request.ShipmentLines }
     *     
     */
    public Final_Release_Request.ShipmentLines getShipmentLines() {
        return shipmentLines;
    }

    /**
     * Sets the value of the shipmentLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Final_Release_Request.ShipmentLines }
     *     
     */
    public void setShipmentLines(Final_Release_Request.ShipmentLines value) {
        this.shipmentLines = value;
    }

    /**
     * Gets the value of the enterpriseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseCode() {
        return enterpriseCode;
    }

    /**
     * Sets the value of the enterpriseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseCode(String value) {
        this.enterpriseCode = value;
    }

    /**
     * Gets the value of the sellerOrganizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getSellerOrganizationCode() {
        return sellerOrganizationCode;
    }

    /**
     * Sets the value of the sellerOrganizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setSellerOrganizationCode(Short value) {
        this.sellerOrganizationCode = value;
    }

    /**
     * Gets the value of the shipNode property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getShipNode() {
        return shipNode;
    }

    /**
     * Sets the value of the shipNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setShipNode(Short value) {
        this.shipNode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnDerivedTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnHostOrderSystemIdentifier" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Extn {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "ExtnHostOrderReference")
        protected String extnHostOrderReference;
        @XmlAttribute(name = "ExtnDerivedTransactionType")
        protected String extnDerivedTransactionType;
        @XmlAttribute(name = "ExtnHostOrderSystemIdentifier")
        protected Byte extnHostOrderSystemIdentifier;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the extnHostOrderReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnHostOrderReference() {
            return extnHostOrderReference;
        }

        /**
         * Sets the value of the extnHostOrderReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnHostOrderReference(String value) {
            this.extnHostOrderReference = value;
        }

        /**
         * Gets the value of the extnDerivedTransactionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnDerivedTransactionType() {
            return extnDerivedTransactionType;
        }

        /**
         * Sets the value of the extnDerivedTransactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnDerivedTransactionType(String value) {
            this.extnDerivedTransactionType = value;
        }

        /**
         * Gets the value of the extnHostOrderSystemIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getExtnHostOrderSystemIdentifier() {
            return extnHostOrderSystemIdentifier;
        }

        /**
         * Sets the value of the extnHostOrderSystemIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setExtnHostOrderSystemIdentifier(Byte value) {
            this.extnHostOrderSystemIdentifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ShipmentLine">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Extn">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="ExtnHostOrderLineReference" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                           &lt;attribute name="ExtnTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="ExtnSKUCode" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="ExtnSVSRemEntriesReqd" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}float" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shipmentLine"
    })
    public static class ShipmentLines {

        @XmlElement(name = "ShipmentLine", required = true)
        protected Final_Release_Request.ShipmentLines.ShipmentLine shipmentLine;

        /**
         * Gets the value of the shipmentLine property.
         * 
         * @return
         *     possible object is
         *     {@link Final_Release_Request.ShipmentLines.ShipmentLine }
         *     
         */
        public Final_Release_Request.ShipmentLines.ShipmentLine getShipmentLine() {
            return shipmentLine;
        }

        /**
         * Sets the value of the shipmentLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link Final_Release_Request.ShipmentLines.ShipmentLine }
         *     
         */
        public void setShipmentLine(Final_Release_Request.ShipmentLines.ShipmentLine value) {
            this.shipmentLine = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Extn">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="ExtnHostOrderLineReference" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                 &lt;attribute name="ExtnTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="ExtnSKUCode" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="ExtnSVSRemEntriesReqd" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Quantity" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "extn"
        })
        public static class ShipmentLine {

            @XmlElement(name = "Extn", required = true)
            protected Final_Release_Request.ShipmentLines.ShipmentLine.Extn extn;
            @XmlAttribute(name = "Quantity")
            protected Float quantity;

            /**
             * Gets the value of the extn property.
             * 
             * @return
             *     possible object is
             *     {@link Final_Release_Request.ShipmentLines.ShipmentLine.Extn }
             *     
             */
            public Final_Release_Request.ShipmentLines.ShipmentLine.Extn getExtn() {
                return extn;
            }

            /**
             * Sets the value of the extn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Final_Release_Request.ShipmentLines.ShipmentLine.Extn }
             *     
             */
            public void setExtn(Final_Release_Request.ShipmentLines.ShipmentLine.Extn value) {
                this.extn = value;
            }

            /**
             * Gets the value of the quantity property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getQuantity() {
                return quantity;
            }

            /**
             * Sets the value of the quantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setQuantity(Float value) {
                this.quantity = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="ExtnHostOrderLineReference" type="{http://www.w3.org/2001/XMLSchema}short" />
             *       &lt;attribute name="ExtnTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="ExtnSKUCode" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="ExtnSVSRemEntriesReqd" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Extn {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "ExtnHostOrderLineReference")
                protected Short extnHostOrderLineReference;
                @XmlAttribute(name = "ExtnTransactionType")
                protected String extnTransactionType;
                @XmlAttribute(name = "ExtnSKUCode")
                protected Integer extnSKUCode;
                @XmlAttribute(name = "ExtnSVSRemEntriesReqd")
                protected String extnSVSRemEntriesReqd;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the extnHostOrderLineReference property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *     
                 */
                public Short getExtnHostOrderLineReference() {
                    return extnHostOrderLineReference;
                }

                /**
                 * Sets the value of the extnHostOrderLineReference property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *     
                 */
                public void setExtnHostOrderLineReference(Short value) {
                    this.extnHostOrderLineReference = value;
                }

                /**
                 * Gets the value of the extnTransactionType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExtnTransactionType() {
                    return extnTransactionType;
                }

                /**
                 * Sets the value of the extnTransactionType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExtnTransactionType(String value) {
                    this.extnTransactionType = value;
                }

                /**
                 * Gets the value of the extnSKUCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getExtnSKUCode() {
                    return extnSKUCode;
                }

                /**
                 * Sets the value of the extnSKUCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setExtnSKUCode(Integer value) {
                    this.extnSKUCode = value;
                }

                /**
                 * Gets the value of the extnSVSRemEntriesReqd property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExtnSVSRemEntriesReqd() {
                    return extnSVSRemEntriesReqd;
                }

                /**
                 * Sets the value of the extnSVSRemEntriesReqd property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExtnSVSRemEntriesReqd(String value) {
                    this.extnSVSRemEntriesReqd = value;
                }

            }

        }

    }

}
