//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 11:17:43 PM IST 
//


package com.Thd.Request.JavaBeans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An Pick_Confirmation_Object_Factory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class Pick_Confirmation_Object_Factory {


    /**
     * Create a new Pick_Confirmation_Object_Factory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public Pick_Confirmation_Object_Factory() {
    }

    /**
     * Create an instance of {@link Pick_Confirmation.Shipment.ShipmentLines }
     * 
     */
    public Pick_Confirmation.Shipment.ShipmentLines createShipmentsShipmentShipmentLines() {
        return new Pick_Confirmation.Shipment.ShipmentLines();
    }

    /**
     * Create an instance of {@link Pick_Confirmation }
     * 
     */
    public Pick_Confirmation createShipments() {
        return new Pick_Confirmation();
    }

    /**
     * Create an instance of {@link Pick_Confirmation.Extn }
     * 
     */
    public Pick_Confirmation.Extn createShipmentsExtn() {
        return new Pick_Confirmation.Extn();
    }

    /**
     * Create an instance of {@link Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Order }
     * 
     */
    public Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Order createShipmentsShipmentShipmentLinesShipmentLineOrder() {
        return new Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Order();
    }

    /**
     * Create an instance of {@link Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine }
     * 
     */
    public Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine createShipmentsShipmentShipmentLinesShipmentLine() {
        return new Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine();
    }

    /**
     * Create an instance of {@link Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Order.Extn }
     * 
     */
    public Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Order.Extn createShipmentsShipmentShipmentLinesShipmentLineOrderExtn() {
        return new Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Order.Extn();
    }

    /**
     * Create an instance of {@link Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Extn }
     * 
     */
    public Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Extn createShipmentsShipmentShipmentLinesShipmentLineExtn() {
        return new Pick_Confirmation.Shipment.ShipmentLines.ShipmentLine.Extn();
    }

    /**
     * Create an instance of {@link Pick_Confirmation.Shipment }
     * 
     */
    public Pick_Confirmation.Shipment createShipmentsShipment() {
        return new Pick_Confirmation.Shipment();
    }

}
