//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 10:37:06 AM IST 
//


package com.Thd.Request.JavaBeans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An Recall_Order_Object_Factory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class Recall_Order_Object_Factory {


    /**
     * Create a new Recall_Order_Object_Factory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public Recall_Order_Object_Factory() {
    }

    /**
     * Create an instance of {@link Recall_Order.Extn }
     * 
     */
    public Recall_Order.Extn createOrderExtn() {
        return new Recall_Order.Extn();
    }

    /**
     * Create an instance of {@link Recall_Order }
     * 
     */
    public Recall_Order createOrder() {
        return new Recall_Order();
    }

}
