//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 10:37:06 AM IST 
//


package com.Thd.Request.JavaBeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Extn">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeReleaseDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeInstructions" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeAuditDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeAlertDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnPutOrderOnLock" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnUserId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeEventDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeStatusDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeWorkOrderDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludePurchaseOrderDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnIncludeReturnOrderDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="EnterpriseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="MaximumRecords" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extn"
})
@XmlRootElement(name = "Order")
public class Recall_Order {

    @XmlElement(name = "Extn", required = true)
    protected Recall_Order.Extn extn;
    @XmlAttribute(name = "EnterpriseCode")
    protected String enterpriseCode;
    @XmlAttribute(name = "DocumentType")
    protected Byte documentType;
    @XmlAttribute(name = "MaximumRecords")
    protected Byte maximumRecords;

    /**
     * Gets the value of the extn property.
     * 
     * @return
     *     possible object is
     *     {@link Recall_Order.Extn }
     *     
     */
    public Recall_Order.Extn getExtn() {
        return extn;
    }

    /**
     * Sets the value of the extn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recall_Order.Extn }
     *     
     */
    public void setExtn(Recall_Order.Extn value) {
        this.extn = value;
    }

    /**
     * Gets the value of the enterpriseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseCode() {
        return enterpriseCode;
    }

    /**
     * Sets the value of the enterpriseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseCode(String value) {
        this.enterpriseCode = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setDocumentType(Byte value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the maximumRecords property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getMaximumRecords() {
        return maximumRecords;
    }

    /**
     * Sets the value of the maximumRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setMaximumRecords(Byte value) {
        this.maximumRecords = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeReleaseDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeInstructions" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeAuditDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeAlertDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnPutOrderOnLock" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnUserId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeEventDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeStatusDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeWorkOrderDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludePurchaseOrderDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnIncludeReturnOrderDetails" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Extn {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "ExtnHostOrderReference")
        protected String extnHostOrderReference;
        @XmlAttribute(name = "ExtnIncludeReleaseDetails")
        protected String extnIncludeReleaseDetails;
        @XmlAttribute(name = "ExtnIncludeInstructions")
        protected String extnIncludeInstructions;
        @XmlAttribute(name = "ExtnIncludeAuditDetails")
        protected String extnIncludeAuditDetails;
        @XmlAttribute(name = "ExtnIncludeAlertDetails")
        protected String extnIncludeAlertDetails;
        @XmlAttribute(name = "ExtnPutOrderOnLock")
        protected String extnPutOrderOnLock;
        @XmlAttribute(name = "ExtnUserId")
        protected String extnUserId;
        @XmlAttribute(name = "ExtnIncludeEventDetails")
        protected String extnIncludeEventDetails;
        @XmlAttribute(name = "ExtnIncludeStatusDetails")
        protected String extnIncludeStatusDetails;
        @XmlAttribute(name = "ExtnIncludeWorkOrderDetails")
        protected String extnIncludeWorkOrderDetails;
        @XmlAttribute(name = "ExtnIncludePurchaseOrderDetails")
        protected String extnIncludePurchaseOrderDetails;
        @XmlAttribute(name = "ExtnIncludeReturnOrderDetails")
        protected String extnIncludeReturnOrderDetails;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the extnHostOrderReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnHostOrderReference() {
            return extnHostOrderReference;
        }

        /**
         * Sets the value of the extnHostOrderReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnHostOrderReference(String value) {
            this.extnHostOrderReference = value;
        }

        /**
         * Gets the value of the extnIncludeReleaseDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeReleaseDetails() {
            return extnIncludeReleaseDetails;
        }

        /**
         * Sets the value of the extnIncludeReleaseDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeReleaseDetails(String value) {
            this.extnIncludeReleaseDetails = value;
        }

        /**
         * Gets the value of the extnIncludeInstructions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeInstructions() {
            return extnIncludeInstructions;
        }

        /**
         * Sets the value of the extnIncludeInstructions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeInstructions(String value) {
            this.extnIncludeInstructions = value;
        }

        /**
         * Gets the value of the extnIncludeAuditDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeAuditDetails() {
            return extnIncludeAuditDetails;
        }

        /**
         * Sets the value of the extnIncludeAuditDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeAuditDetails(String value) {
            this.extnIncludeAuditDetails = value;
        }

        /**
         * Gets the value of the extnIncludeAlertDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeAlertDetails() {
            return extnIncludeAlertDetails;
        }

        /**
         * Sets the value of the extnIncludeAlertDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeAlertDetails(String value) {
            this.extnIncludeAlertDetails = value;
        }

        /**
         * Gets the value of the extnPutOrderOnLock property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnPutOrderOnLock() {
            return extnPutOrderOnLock;
        }

        /**
         * Sets the value of the extnPutOrderOnLock property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnPutOrderOnLock(String value) {
            this.extnPutOrderOnLock = value;
        }

        /**
         * Gets the value of the extnUserId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnUserId() {
            return extnUserId;
        }

        /**
         * Sets the value of the extnUserId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnUserId(String value) {
            this.extnUserId = value;
        }

        /**
         * Gets the value of the extnIncludeEventDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeEventDetails() {
            return extnIncludeEventDetails;
        }

        /**
         * Sets the value of the extnIncludeEventDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeEventDetails(String value) {
            this.extnIncludeEventDetails = value;
        }

        /**
         * Gets the value of the extnIncludeStatusDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeStatusDetails() {
            return extnIncludeStatusDetails;
        }

        /**
         * Sets the value of the extnIncludeStatusDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeStatusDetails(String value) {
            this.extnIncludeStatusDetails = value;
        }

        /**
         * Gets the value of the extnIncludeWorkOrderDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeWorkOrderDetails() {
            return extnIncludeWorkOrderDetails;
        }

        /**
         * Sets the value of the extnIncludeWorkOrderDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeWorkOrderDetails(String value) {
            this.extnIncludeWorkOrderDetails = value;
        }

        /**
         * Gets the value of the extnIncludePurchaseOrderDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludePurchaseOrderDetails() {
            return extnIncludePurchaseOrderDetails;
        }

        /**
         * Sets the value of the extnIncludePurchaseOrderDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludePurchaseOrderDetails(String value) {
            this.extnIncludePurchaseOrderDetails = value;
        }

        /**
         * Gets the value of the extnIncludeReturnOrderDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnIncludeReturnOrderDetails() {
            return extnIncludeReturnOrderDetails;
        }

        /**
         * Sets the value of the extnIncludeReturnOrderDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnIncludeReturnOrderDetails(String value) {
            this.extnIncludeReturnOrderDetails = value;
        }

    }

}
