//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 01:56:38 PM IST 
//


package com.Thd.Response.JavaBeans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An Final_Release_Response_Object_Factory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class Final_Release_Response_Object_Factory {


    /**
     * Create a new Final_Release_Response_Object_Factory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public Final_Release_Response_Object_Factory() {
    }

    /**
     * Create an instance of {@link Final_Release_Response.ShipmentLines.ShipmentLine.Extn }
     * 
     */
    public Final_Release_Response.ShipmentLines.ShipmentLine.Extn createShipmentShipmentLinesShipmentLineExtn() {
        return new Final_Release_Response.ShipmentLines.ShipmentLine.Extn();
    }

    /**
     * Create an instance of {@link Final_Release_Response.Extn }
     * 
     */
    public Final_Release_Response.Extn createShipmentExtn() {
        return new Final_Release_Response.Extn();
    }

    /**
     * Create an instance of {@link Final_Release_Response.ShipmentLines }
     * 
     */
    public Final_Release_Response.ShipmentLines createShipmentShipmentLines() {
        return new Final_Release_Response.ShipmentLines();
    }

    /**
     * Create an instance of {@link Final_Release_Response.ShipmentLines.ShipmentLine }
     * 
     */
    public Final_Release_Response.ShipmentLines.ShipmentLine createShipmentShipmentLinesShipmentLine() {
        return new Final_Release_Response.ShipmentLines.ShipmentLine();
    }

    /**
     * Create an instance of {@link Final_Release_Response }
     * 
     */
    public Final_Release_Response createShipment() {
        return new Final_Release_Response();
    }

}
