//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.21 at 02:00:37 PM IST 
//


package com.Thd.Response.JavaBeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Extn">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="ExtnDerivedTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ExtnMessageGeneratedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Shipment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ShipmentLines">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ShipmentLine">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Extn">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="ExtnFIQuantity" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                               &lt;attribute name="ExtnPickLocation" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                               &lt;attribute name="ExtnPickedQuantity" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Order">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Extn">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="ShipmentLineNo" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="TotalNumberOfRecords" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="EnterpriseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OrderNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="RequestedShipmentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="ShipNode" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="ShipmentNo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="AnalyzeFor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ShipNode" type="{http://www.w3.org/2001/XMLSchema}short" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "extn",
    "shipment"
})
@XmlRootElement(name = "Shipments")
public class PICK {

    @XmlElement(name = "Extn", required = true)
    protected PICK.Extn extn;
    @XmlElement(name = "Shipment", required = true)
    protected PICK.Shipment shipment;
    @XmlAttribute(name = "AnalyzeFor")
    protected String analyzeFor;
    @XmlAttribute(name = "ShipNode")
    protected Short shipNode;

    /**
     * Gets the value of the extn property.
     * 
     * @return
     *     possible object is
     *     {@link PICK.Extn }
     *     
     */
    public PICK.Extn getExtn() {
        return extn;
    }

    /**
     * Sets the value of the extn property.
     * 
     * @param value
     *     allowed object is
     *     {@link PICK.Extn }
     *     
     */
    public void setExtn(PICK.Extn value) {
        this.extn = value;
    }

    /**
     * Gets the value of the shipment property.
     * 
     * @return
     *     possible object is
     *     {@link PICK.Shipment }
     *     
     */
    public PICK.Shipment getShipment() {
        return shipment;
    }

    /**
     * Sets the value of the shipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PICK.Shipment }
     *     
     */
    public void setShipment(PICK.Shipment value) {
        this.shipment = value;
    }

    /**
     * Gets the value of the analyzeFor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalyzeFor() {
        return analyzeFor;
    }

    /**
     * Sets the value of the analyzeFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalyzeFor(String value) {
        this.analyzeFor = value;
    }

    /**
     * Gets the value of the shipNode property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getShipNode() {
        return shipNode;
    }

    /**
     * Sets the value of the shipNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setShipNode(Short value) {
        this.shipNode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="ExtnDerivedTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ExtnMessageGeneratedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Extn {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "ExtnDerivedTransactionType")
        protected String extnDerivedTransactionType;
        @XmlAttribute(name = "ExtnHostOrderReference")
        protected String extnHostOrderReference;
        @XmlAttribute(name = "ExtnMessageGeneratedTime")
        protected Long extnMessageGeneratedTime;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the extnDerivedTransactionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnDerivedTransactionType() {
            return extnDerivedTransactionType;
        }

        /**
         * Sets the value of the extnDerivedTransactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnDerivedTransactionType(String value) {
            this.extnDerivedTransactionType = value;
        }

        /**
         * Gets the value of the extnHostOrderReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtnHostOrderReference() {
            return extnHostOrderReference;
        }

        /**
         * Sets the value of the extnHostOrderReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtnHostOrderReference(String value) {
            this.extnHostOrderReference = value;
        }

        /**
         * Gets the value of the extnMessageGeneratedTime property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getExtnMessageGeneratedTime() {
            return extnMessageGeneratedTime;
        }

        /**
         * Sets the value of the extnMessageGeneratedTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setExtnMessageGeneratedTime(Long value) {
            this.extnMessageGeneratedTime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ShipmentLines">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ShipmentLine">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Extn">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="ExtnFIQuantity" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                                     &lt;attribute name="ExtnPickLocation" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                                     &lt;attribute name="ExtnPickedQuantity" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Order">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Extn">
     *                                         &lt;complexType>
     *                                           &lt;simpleContent>
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                               &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                             &lt;/extension>
     *                                           &lt;/simpleContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="ShipmentLineNo" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="TotalNumberOfRecords" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="DocumentType" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="EnterpriseCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OrderNo" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="RequestedShipmentDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="ShipNode" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="ShipmentNo" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "shipmentLines"
    })
    public static class Shipment {

        @XmlElement(name = "ShipmentLines", required = true)
        protected PICK.Shipment.ShipmentLines shipmentLines;
        @XmlAttribute(name = "DocumentType")
        protected Byte documentType;
        @XmlAttribute(name = "EnterpriseCode")
        protected String enterpriseCode;
        @XmlAttribute(name = "OrderNo")
        protected String orderNo;
        @XmlAttribute(name = "RequestedShipmentDate")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar requestedShipmentDate;
        @XmlAttribute(name = "ShipNode")
        protected Short shipNode;
        @XmlAttribute(name = "ShipmentNo")
        protected Integer shipmentNo;

        /**
         * Gets the value of the shipmentLines property.
         * 
         * @return
         *     possible object is
         *     {@link PICK.Shipment.ShipmentLines }
         *     
         */
        public PICK.Shipment.ShipmentLines getShipmentLines() {
            return shipmentLines;
        }

        /**
         * Sets the value of the shipmentLines property.
         * 
         * @param value
         *     allowed object is
         *     {@link PICK.Shipment.ShipmentLines }
         *     
         */
        public void setShipmentLines(PICK.Shipment.ShipmentLines value) {
            this.shipmentLines = value;
        }

        /**
         * Gets the value of the documentType property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getDocumentType() {
            return documentType;
        }

        /**
         * Sets the value of the documentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setDocumentType(Byte value) {
            this.documentType = value;
        }

        /**
         * Gets the value of the enterpriseCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnterpriseCode() {
            return enterpriseCode;
        }

        /**
         * Sets the value of the enterpriseCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnterpriseCode(String value) {
            this.enterpriseCode = value;
        }

        /**
         * Gets the value of the orderNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderNo() {
            return orderNo;
        }

        /**
         * Sets the value of the orderNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderNo(String value) {
            this.orderNo = value;
        }

        /**
         * Gets the value of the requestedShipmentDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getRequestedShipmentDate() {
            return requestedShipmentDate;
        }

        /**
         * Sets the value of the requestedShipmentDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setRequestedShipmentDate(XMLGregorianCalendar value) {
            this.requestedShipmentDate = value;
        }

        /**
         * Gets the value of the shipNode property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getShipNode() {
            return shipNode;
        }

        /**
         * Sets the value of the shipNode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setShipNode(Short value) {
            this.shipNode = value;
        }

        /**
         * Gets the value of the shipmentNo property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getShipmentNo() {
            return shipmentNo;
        }

        /**
         * Sets the value of the shipmentNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setShipmentNo(Integer value) {
            this.shipmentNo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ShipmentLine">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Extn">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="ExtnFIQuantity" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                           &lt;attribute name="ExtnPickLocation" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                           &lt;attribute name="ExtnPickedQuantity" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Order">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Extn">
         *                               &lt;complexType>
         *                                 &lt;simpleContent>
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                     &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                                   &lt;/extension>
         *                                 &lt;/simpleContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="ShipmentLineNo" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="TotalNumberOfRecords" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shipmentLine"
        })
        public static class ShipmentLines {

            @XmlElement(name = "ShipmentLine", required = true)
            protected PICK.Shipment.ShipmentLines.ShipmentLine shipmentLine;
            @XmlAttribute(name = "TotalNumberOfRecords")
            protected Byte totalNumberOfRecords;

            /**
             * Gets the value of the shipmentLine property.
             * 
             * @return
             *     possible object is
             *     {@link PICK.Shipment.ShipmentLines.ShipmentLine }
             *     
             */
            public PICK.Shipment.ShipmentLines.ShipmentLine getShipmentLine() {
                return shipmentLine;
            }

            /**
             * Sets the value of the shipmentLine property.
             * 
             * @param value
             *     allowed object is
             *     {@link PICK.Shipment.ShipmentLines.ShipmentLine }
             *     
             */
            public void setShipmentLine(PICK.Shipment.ShipmentLines.ShipmentLine value) {
                this.shipmentLine = value;
            }

            /**
             * Gets the value of the totalNumberOfRecords property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getTotalNumberOfRecords() {
                return totalNumberOfRecords;
            }

            /**
             * Sets the value of the totalNumberOfRecords property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setTotalNumberOfRecords(Byte value) {
                this.totalNumberOfRecords = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Extn">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="ExtnFIQuantity" type="{http://www.w3.org/2001/XMLSchema}float" />
             *                 &lt;attribute name="ExtnPickLocation" type="{http://www.w3.org/2001/XMLSchema}short" />
             *                 &lt;attribute name="ExtnPickedQuantity" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Order">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Extn">
             *                     &lt;complexType>
             *                       &lt;simpleContent>
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                           &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                         &lt;/extension>
             *                       &lt;/simpleContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="ShipmentLineNo" type="{http://www.w3.org/2001/XMLSchema}byte" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "extn",
                "order"
            })
            public static class ShipmentLine {

                @XmlElement(name = "Extn", required = true)
                protected PICK.Shipment.ShipmentLines.ShipmentLine.Extn extn;
                @XmlElement(name = "Order", required = true)
                protected PICK.Shipment.ShipmentLines.ShipmentLine.Order order;
                @XmlAttribute(name = "ShipmentLineNo")
                protected Byte shipmentLineNo;

                /**
                 * Gets the value of the extn property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PICK.Shipment.ShipmentLines.ShipmentLine.Extn }
                 *     
                 */
                public PICK.Shipment.ShipmentLines.ShipmentLine.Extn getExtn() {
                    return extn;
                }

                /**
                 * Sets the value of the extn property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PICK.Shipment.ShipmentLines.ShipmentLine.Extn }
                 *     
                 */
                public void setExtn(PICK.Shipment.ShipmentLines.ShipmentLine.Extn value) {
                    this.extn = value;
                }

                /**
                 * Gets the value of the order property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PICK.Shipment.ShipmentLines.ShipmentLine.Order }
                 *     
                 */
                public PICK.Shipment.ShipmentLines.ShipmentLine.Order getOrder() {
                    return order;
                }

                /**
                 * Sets the value of the order property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PICK.Shipment.ShipmentLines.ShipmentLine.Order }
                 *     
                 */
                public void setOrder(PICK.Shipment.ShipmentLines.ShipmentLine.Order value) {
                    this.order = value;
                }

                /**
                 * Gets the value of the shipmentLineNo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Byte }
                 *     
                 */
                public Byte getShipmentLineNo() {
                    return shipmentLineNo;
                }

                /**
                 * Sets the value of the shipmentLineNo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Byte }
                 *     
                 */
                public void setShipmentLineNo(Byte value) {
                    this.shipmentLineNo = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="ExtnFIQuantity" type="{http://www.w3.org/2001/XMLSchema}float" />
                 *       &lt;attribute name="ExtnPickLocation" type="{http://www.w3.org/2001/XMLSchema}short" />
                 *       &lt;attribute name="ExtnPickedQuantity" type="{http://www.w3.org/2001/XMLSchema}byte" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Extn {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "ExtnFIQuantity")
                    protected Float extnFIQuantity;
                    @XmlAttribute(name = "ExtnPickLocation")
                    protected Short extnPickLocation;
                    @XmlAttribute(name = "ExtnPickedQuantity")
                    protected Byte extnPickedQuantity;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the extnFIQuantity property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public Float getExtnFIQuantity() {
                        return extnFIQuantity;
                    }

                    /**
                     * Sets the value of the extnFIQuantity property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setExtnFIQuantity(Float value) {
                        this.extnFIQuantity = value;
                    }

                    /**
                     * Gets the value of the extnPickLocation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Short }
                     *     
                     */
                    public Short getExtnPickLocation() {
                        return extnPickLocation;
                    }

                    /**
                     * Sets the value of the extnPickLocation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Short }
                     *     
                     */
                    public void setExtnPickLocation(Short value) {
                        this.extnPickLocation = value;
                    }

                    /**
                     * Gets the value of the extnPickedQuantity property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Byte }
                     *     
                     */
                    public Byte getExtnPickedQuantity() {
                        return extnPickedQuantity;
                    }

                    /**
                     * Sets the value of the extnPickedQuantity property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Byte }
                     *     
                     */
                    public void setExtnPickedQuantity(Byte value) {
                        this.extnPickedQuantity = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Extn">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "extn"
                })
                public static class Order {

                    @XmlElement(name = "Extn", required = true)
                    protected PICK.Shipment.ShipmentLines.ShipmentLine.Order.Extn extn;

                    /**
                     * Gets the value of the extn property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link PICK.Shipment.ShipmentLines.ShipmentLine.Order.Extn }
                     *     
                     */
                    public PICK.Shipment.ShipmentLines.ShipmentLine.Order.Extn getExtn() {
                        return extn;
                    }

                    /**
                     * Sets the value of the extn property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link PICK.Shipment.ShipmentLines.ShipmentLine.Order.Extn }
                     *     
                     */
                    public void setExtn(PICK.Shipment.ShipmentLines.ShipmentLine.Order.Extn value) {
                        this.extn = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="ExtnHostOrderReference" type="{http://www.w3.org/2001/XMLSchema}string" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Extn {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(name = "ExtnHostOrderReference")
                        protected String extnHostOrderReference;

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the extnHostOrderReference property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getExtnHostOrderReference() {
                            return extnHostOrderReference;
                        }

                        /**
                         * Sets the value of the extnHostOrderReference property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setExtnHostOrderReference(String value) {
                            this.extnHostOrderReference = value;
                        }

                    }

                }

            }

        }

    }

}
